name: banner_carousel
description: A Widget horizontal scrollable list with indicator and animations.
version: 1.2.1
homepage: https://github.com/MaiaraM/banner_carousel

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
